export const SET_FILTER = 'SET_FILTER';
export const GET_ALL_PHOTOS_REQUEST = 'GET_ALL_PHOTOS_REQUEST';
export const GET_ALL_PHOTOS_SUCCESS = 'GET_ALL_PHOTOS_SUCCESS';
export const GET_VECTOR_SUCCESS = 'GET_VECTOR_SUCCESS';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const GET_PHOTOS_FAILED = 'GET_PHOTOS_FAILED';
export const PIXABAY_API = 'https://pixabay.com/api/?key=4643588-c041075ab4893ac7a50c51f21';
